---
- name: "download.curl: Ensure directory of download_to"
  file:
    path: "{{ download_to | expanduser | dirname }}"
    state: directory

- name: "download.curl: Curl"
  get_url:
    url: "{{ download_from }}"
    url_username: "{{ download_user | default(omit) }}"
    url_password: "{{ download_pass | default(omit) }}"
    dest: "{{ download_to }}"
    force: "{{ download_overwrite }}"
    validate_certs: "{{ download_secure }}"
