---
- name: "download.curl: Ensure dependencies"
  become: yes
  become_user: root
  yum:
    name: "curl"
    state: "latest"

- name: "download.curl: Curl"
  get_url:
    url: "{{ download_from }}"
    url_username: "{{ download_user | default(omit) }}"
    url_password: "{{ download_pass | default(omit) }}"
    dest: "{{ download_to }}"
    force: "{{ download_overwrite }}"
    validate_certs: "{{ download_secure }}"
