---
- name: "download.gs: Google Storage"
  gc_storage:
    gs_access_key: "{{ download_user | default(omit) }}"
    gs_secret_key: "{{ download_pass | default(omit) }}"
    region: "{{ download_from_region | default(omit) }}"
    bucket: "{{ download_from_bucket }}"
    object: "{{ download_from }}"
    dest: "{{ download_to }}"
    force: "{{ download_overwrite }}"
    permission: "{{ (download_user|default(False)) | ternary('private', 'public-read') }}"
    mode: "get"
