---
- name: "download.s3: Ensure python-boto3"
  yum:
    name: "python-boto3"
    state: "latest"

- name: "download.s3: Amazon S3"
  aws_s3:
    aws_access_key: "{{ download_user | default(omit) }}"
    aws_secret_key: "{{ download_pass | default(omit) }}"
    region: "{{ download_region | default(omit) }}"
    bucket: "{{ download_from_bucket }}"
    object: "{{ download_from }}"
    dest: "{{ download_to }}"
    force: "{{ download_overwrite }}"
    validate_certs: "{{ download_secure }}"
    mode: "get"
