---
- name: "download.s3: Ensure directory of download_to"
  file:
    path: "{{ download_to | expanduser | dirname }}"
    state: directory

- name: "download.s3: Amazon S3"
  aws_s3:
    aws_access_key: "{{ download_user | default(omit) }}"
    aws_secret_key: "{{ download_pass | default(omit) }}"
    region: "{{ download_from_region  | default(omit) }}"
    bucket: "{{ download_from_bucket }}"
    object: "{{ download_from }}"
    dest: "{{ download_to }}"
    force: "{{ download_overwrite }}"
    permission: "{{ (download_user|default(False)) | ternary('private', 'public-read') }}"
    validate_certs: "{{ download_secure }}"
    mode: "get"
